/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#dae3ee',
        'outline': '#849495',
        'on-surface': '#dae3ee',
        'inverse-primary': '#00696f',
        'surface': '#0b141c',
        'surface-dim': '#0b141c',
        'secondary': '#c3c6cf',
        'primary-fixed-dim': '#00dbe7',
        'on-primary': '#00363a',
        'secondary-fixed': '#dfe2eb',
        'outline-variant': '#3a494b',
        'on-primary-fixed-variant': '#004f54',
        'primary': '#e1fdff',
        'on-primary-container': '#006a71',
        'surface-container-highest': '#2d363e',
        'error': '#ffb4ab',
        'inverse-on-surface': '#29313a',
        'primary-fixed': '#74f5ff',
        'secondary-container': '#454950',
        'surface-container-high': '#222b33',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dae3ee',
        'tertiary': '#f5f7ff',
        'surface-bright': '#313a43',
        'surface-tint': '#00dbe7',
        'surface-container-low': '#141c24',
        'on-primary-fixed': '#002022',
        'error-container': '#93000a',
        'primary-container': '#00f2ff',
        'tertiary-container': '#d7dbe5',
        'on-error': '#690005',
        'surface-variant': '#2d363e',
        'surface-container-lowest': '#060f16',
        'on-tertiary': '#2c3138',
        'background': '#0b141c',
        'on-secondary': '#2d3137',
        'on-surface-variant': '#b9cacb',
        'on-secondary-container': '#b5b8c1',
        'surface-container': '#182028',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        heading: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'pulse-ring': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.8)', opacity: '0' },
        },
        'radar-sweep': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'scan-line': {
          '0%': { transform: 'translateY(0%)' },
          '100%': { transform: 'translateY(400%)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 6px #00dbe7, 0 0 12px #00dbe780' },
          '50%': { boxShadow: '0 0 18px #00dbe7, 0 0 36px #00dbe740' },
        },
        'blink': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'glitch': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-2px)' },
          '40%': { transform: 'translateX(2px)' },
          '60%': { transform: 'translateX(-1px)' },
          '80%': { transform: 'translateX(1px)' },
        },
      },
      animation: {
        'pulse-ring': 'pulse-ring 2s ease-in-out infinite',
        'radar-sweep': 'radar-sweep 4s linear infinite',
        'scan-line': 'scan-line 2.5s linear infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'blink': 'blink 1s step-start infinite',
        'glitch': 'glitch 0.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
